### ISSUE TITLE
dotnet tool does not work

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#152]
.config\tools-manifest.json:
```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "csharpasyncgenerator.tool": {
      "version": "0.19.0",
      "commands": [
        "async-generator"
      ]
    }
  }
}
```

.NET SDK 5.0.100
```
PS C:\Projects\Private\nhibernate-core\src> dotnet async-generator
AsyncGenerator

Generating async code started
Opening project 'C:\Projects\Private\nhibernate-core\src\NHibernate\NHibernate.csproj' started
Opening project 'C:\Projects\Private\nhibernate-core\src\NHibernate\NHibernate.csproj' completed
Configuring project prior analyzation started
Configuring project prior analyzation completed
Compiling project 'NHibernate' started
Compiling project 'NHibernate' completed
Initializing registered plugins for project 'NHibernate' started
System.InvalidOperationException: Unable to find System.Threading.Tasks.Task type
   at AsyncGenerator.Internal.ThreadSleepAsyncCounterpartFinder.Initialize(Project project, IProjectConfiguration configuration, Compilation compilation) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\Internal\ThreadSleepAsyncCounterpartFinder.cs:line 30
   at AsyncGenerator.AsyncCodeGenerator.GenerateProject(ProjectData projectData, ILoggerFactory loggerFactory, ILogger logger, CancellationToken cancellationToken)
   at AsyncGenerator.AsyncCodeGenerator.GenerateAsync(AsyncCodeConfiguration configuration, CancellationToken cancellationToken) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\AsyncCodeGenerator.cs:line 86
   at AsyncGenerator.CommandLine.Program.Main(String[] args) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator.CommandLine\Program.cs:line 59   
```
.NET SDK 3.1.100
```
PS C:\Projects\Private\nhibernate-core\src> dotnet async-generator
AsyncGenerator

Generating async code started
Opening project 'C:\Projects\Private\nhibernate-core\src\NHibernate\NHibernate.csproj' started
System.InvalidOperationException: One or more errors occurred while opening the project:
Msbuild failed when processing the file 'C:\Projects\Private\nhibernate-core\src\NHibernate\NHibernate.csproj' with message: C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets: (234, 5): Error reading assets file: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
Hint: For suppressing irrelevant errors use SuppressDiagnosticFailures option.
   at AsyncGenerator.AsyncCodeGenerator.CheckForErrors(MSBuildWorkspace workspace, String itemType, ImmutableArray`1 supressFailuresPredicates, ILogger logger) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\AsyncCodeGenerator.cs:line 436
   at AsyncGenerator.AsyncCodeGenerator.OpenProject(MSBuildWorkspace workspace, String filePath, ImmutableArray`1 supressFailuresPredicates, ILogger logger, CancellationToken cancellationToken) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\AsyncCodeGenerator.cs:line 375
   at AsyncGenerator.AsyncCodeGenerator.GenerateAsync(AsyncCodeConfiguration configuration, CancellationToken cancellationToken) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\AsyncCodeGenerator.cs:line 78
   at AsyncGenerator.CommandLine.Program.Main(String[] args) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator.CommandLine\Program.cs:line 63   
```

**Comment by maca88** [comment]
I had the same error as you get with .NET 5.0 when running with `CSharpAsyncGenerator.Tool` and `CSharpAsyncGenerator.CommandLine`, the solution for me was to close all Visual Studio instances. For some reason when opening a project with Roslyn that is at the same time opened with Visual Studio, may cause this issue when switching between target frameworks. Here is my current test with the tool:
```
PS C:\Workspace\Git\nhibernate-core\src> dotnet tool install CSharpAsyncGenerator.Tool
You can invoke the tool from this directory using the following commands: 'dotnet tool run async-generator' or 'dotnet async-generator'.
Tool 'csharpasyncgenerator.tool' (version '0.19.0') was successfully installed. Entry is added to the manifest file C:\Workspace\Git\nhibernate-core\.config\dotnet-tools.json.
PS C:\Workspace\Git\nhibernate-core\src> dotnet --version
5.0.100
PS C:\Workspace\Git\nhibernate-core\src> dotnet async-generator
AsyncGenerator

Generating async code started
Opening project 'C:\Workspace\Git\nhibernate-core\src\NHibernate\NHibernate.csproj' started
Opening project 'C:\Workspace\Git\nhibernate-core\src\NHibernate\NHibernate.csproj' completed
Configuring project prior analyzation started
Configuring project prior analyzation completed
Compiling project 'NHibernate' started
Compiling project 'NHibernate' completed
Initializing registered plugins for project 'NHibernate' started
Initializing registered plugins for project 'NHibernate' completed
Analyzing project 'NHibernate' started
Parsing documents started
Parsing documents completed
Pre-analyzing documents started
Canceling operations...
PS C:\Workspace\Git\nhibernate-core\src> dotnet --version
3.1.200
PS C:\Workspace\Git\nhibernate-core\src> dotnet tool restore
Tool 'csharpasyncgenerator.tool' (version '0.19.0') was restored. Available commands: async-generator

Restore was successful.
PS C:\Workspace\Git\nhibernate-core\src> dotnet async-generator
AsyncGenerator

Generating async code started
Opening project 'C:\Workspace\Git\nhibernate-core\src\NHibernate\NHibernate.csproj' started
Opening project 'C:\Workspace\Git\nhibernate-core\src\NHibernate\NHibernate.csproj' completed
Configuring project prior analyzation started
Configuring project prior analyzation completed
Compiling project 'NHibernate' started
Compiling project 'NHibernate' completed
Initializing registered plugins for project 'NHibernate' started
Initializing registered plugins for project 'NHibernate' completed
Analyzing project 'NHibernate' started
Parsing documents started
Parsing documents completed
Pre-analyzing documents started
Canceling operations...
PS C:\Workspace\Git\nhibernate-core\src> dotnet --version
3.1.101
PS C:\Workspace\Git\nhibernate-core\src> dotnet tool restore
Tool 'csharpasyncgenerator.tool' (version '0.19.0') was restored. Available commands: async-generator

Restore was successful.
PS C:\Workspace\Git\nhibernate-core\src> dotnet async-generator
AsyncGenerator

Generating async code started
Opening project 'C:\Workspace\Git\nhibernate-core\src\NHibernate\NHibernate.csproj' started
Opening project 'C:\Workspace\Git\nhibernate-core\src\NHibernate\NHibernate.csproj' completed
Configuring project prior analyzation started
Configuring project prior analyzation completed
Compiling project 'NHibernate' started
Compiling project 'NHibernate' completed
Initializing registered plugins for project 'NHibernate' started
Initializing registered plugins for project 'NHibernate' completed
Analyzing project 'NHibernate' started
Parsing documents started
Parsing documents completed
Pre-analyzing documents started
Canceling operations...
```

I am not sure for your error in .NET Core `3.1.100`, but the above solution may also work. I tried with version `3.1.101` and works fine for me.

**Comment by hazzik** [comment]
Tried with everything closed. Same errors.

**Comment by hazzik** [comment]
This is the full output for 3.1.100:


PS C:\Projects\Private\nhibernate-core> git clean -fxd
PS C:\Projects\Private\nhibernate-core> dotnet new globaljson --sdk-version 3.1.100
The template "global.json file" was created successfully.
PS C:\Projects\Private\nhibernate-core> dotnet --version
3.1.100
PS C:\Projects\Private\nhibernate-core> dotnet new tool-manifest
The template "Dotnet local tool manifest file" was created successfully.

An update for template pack Microsoft.DotNet.Common.ItemTemplates::3.1.8 is available.
    install command: dotnet new -i Microsoft.DotNet.Common.ItemTemplates::5.0.0
PS C:\Projects\Private\nhibernate-core> dotnet tool install CSharpAsyncGenerator.Tool
You can invoke the tool from this directory using the following commands: 'dotnet tool run async-generator' or 'dotnet async-generator'.
Tool 'csharpasyncgenerator.tool' (version '0.19.0') was successfully installed. Entry is added to the manifest file C:\Projects\Private\nhibernate-core\.config\dotnet-tools.json.
PS C:\Projects\Private\nhibernate-core> cd src
PS C:\Projects\Private\nhibernate-core\src> dotnet async-generator
AsyncGenerator

Generating async code started
Opening project 'C:\Projects\Private\nhibernate-core\src\NHibernate\NHibernate.csproj' started
Opening project 'C:\Projects\Private\nhibernate-core\src\NHibernate\NHibernate.csproj' completed
Configuring project prior analyzation started
Configuring project prior analyzation completed
Compiling project 'NHibernate' started
Compiling project 'NHibernate' completed
Initializing registered plugins for project 'NHibernate' started
System.InvalidOperationException: Unable to find System.Threading.Tasks.Task type
   at AsyncGenerator.Internal.ThreadSleepAsyncCounterpartFinder.Initialize(Project project, IProjectConfiguration configuration, Compilation compilation) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\Internal\ThreadSleepAsyncCounterpartFinder.cs:line 32
   at AsyncGenerator.AsyncCodeGenerator.GenerateProject(ProjectData projectData, ILoggerFactory loggerFactory, ILogger logger, CancellationToken cancellationToken)
   at AsyncGenerator.AsyncCodeGenerator.GenerateAsync(AsyncCodeConfiguration configuration, CancellationToken cancellationToken) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\AsyncCodeGenerator.cs:line 86
   at AsyncGenerator.CommandLine.Program.Main(String[] args) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator.CommandLine\Program.cs:line 63

**Comment by hazzik** [comment]
This is 5.0.100:

```powershell
PS C:\Projects\Private\nhibernate-core> git clean -fxd
PS C:\Projects\Private\nhibernate-core> dotnet new globaljson --sdk-version 5.0.100
The template "global.json file" was created successfully.
PS C:\Projects\Private\nhibernate-core> dotnet new tool-manifest
The template "Dotnet local tool manifest file" was created successfully.
PS C:\Projects\Private\nhibernate-core> dotnet tool install CSharpAsyncGenerator.Tool
You can invoke the tool from this directory using the following commands: 'dotnet tool run async-generator' or 'dotnet async-generator'.
Tool 'csharpasyncgenerator.tool' (version '0.19.0') was successfully installed. Entry is added to the manifest file C:\Projects\Private\nhibernate-core\.config\dotnet-tools.json.
PS C:\Projects\Private\nhibernate-core> cd src
PS C:\Projects\Private\nhibernate-core\src> dotnet async-generator
AsyncGenerator

Generating async code started
Opening project 'C:\Projects\Private\nhibernate-core\src\NHibernate\NHibernate.csproj' started
Opening project 'C:\Projects\Private\nhibernate-core\src\NHibernate\NHibernate.csproj' completed
Configuring project prior analyzation started
Configuring project prior analyzation completed
Compiling project 'NHibernate' started
Compiling project 'NHibernate' completed
Initializing registered plugins for project 'NHibernate' started
System.InvalidOperationException: Unable to find System.Threading.Tasks.Task type
   at AsyncGenerator.Internal.ThreadSleepAsyncCounterpartFinder.Initialize(Project project, IProjectConfiguration configuration, Compilation compilation) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\Internal\ThreadSleepAsyncCounterpartFinder.cs:line 30
   at AsyncGenerator.AsyncCodeGenerator.GenerateProject(ProjectData projectData, ILoggerFactory loggerFactory, ILogger logger, CancellationToken cancellationToken)
   at AsyncGenerator.AsyncCodeGenerator.GenerateAsync(AsyncCodeConfiguration configuration, CancellationToken cancellationToken) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\AsyncCodeGenerator.cs:line 86
   at AsyncGenerator.CommandLine.Program.Main(String[] args) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator.CommandLine\Program.cs:line 59
PS C:\Projects\Private\nhibernate-core\src>
```

**Comment by hazzik** [comment]
Out of curiosity tried `dotnet restore` before `dotnet async-generator`. After that it seems helped on `5.0.100` but not on `3.1.100`.

**Comment by maca88** [comment]
Thanks for the logs, I was able to reproduce and fix the issue. 

> Out of curiosity tried dotnet restore before dotnet async-generator

I forgot to mention that, as you discovered a restore must be done before calling `dotnet async-generator`
