### ISSUE TITLE
NetStandard (or NetCore) version?

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#24]
NHibernate is moving to the NetCore (or NetStandard) worlds, so it would be nice if the tooling would not require having the full .net framework.

I was trying to target netstandard1.6 and the only thing which prevents me to do so is lack of `MSBuildWorkspace` class.

**Comment by maca88** [comment]
After putting some effort on making a .net core version, [I've created](https://github.com/maca88/AsyncGenerator/pull/61) a PR where the generator can be build on .net core by using a custom Roslyn build. Luckily, `MSBuildWorkspace` will be [moved into a separate project](https://github.com/dotnet/roslyn/pull/21670), which will someday target .netstandard 2.0. Based on the current work done for the separation of `MSBuildWorkspace`, I've managed to [modify the project](https://github.com/maca88/roslyn/commit/7d363aa4d5de094ded43830629df8019d6935e6c) to target .netstandard 2.0 and created [nuget packages](https://www.dropbox.com/s/epvvsr8ajkgyamx/RoslynPackages.zip?dl=0) which are used in the mentioned PR.
After some testing I discovered that for some reason, `MSBuildWorkspace` is not able to open a project that has one or more project references, on .net core. Error: 
`C:\Program Files\dotnet\sdk\2.0.0\Microsoft.Common.CurrentVersion.targets: (1485, 5): The "Microsoft.Build.Tasks.ResolveNonMSBuildProjectOutput" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask`.

Additionaly, `MSBuildWorkspace` seems to not support projects with multiple target frameworks (e.g. `net461;netcoreapp2.0`), which applies also for .net framework. Error:
`MSBuildWorkspace can only build projects which contain Compile and CoreCompile targets`. 
This is why the PR contains a [separate test project](https://github.com/maca88/AsyncGenerator/blob/4f62bb3ed9c1b09170ff7dab95a27bc458d4f709/Source/AsyncGenerator.Tests.NETCore/AsyncGenerator.Tests.NETCore.csproj) only for .net core.

**Comment by maca88** [comment]
Update

With the current state of the PR, the tests are now working on .NET Core on Windows, Linux and OSX :). The solution for the above error (`ResolveNonMSBuildProjectOutput`), was to disable [BuildingInsideVisualStudio](https://github.com/maca88/roslyn/commit/b74dddb751efb283dc5c3381b5744f779a090a5d) when opening a project in .NET Core.

**Comment by ngbrown** [comment]
On my .Net core branch, I've tried to run the AsyncGenerator after being able to cleanly compile it with Visual Studio, and have gotten this error:

```
     [exec] 22:03:10,567 INFO  AsyncCodeGenerator:0 - Compiling project 'NHibernate.Test' started
     [exec] 22:03:11,446 INFO  AsyncCodeGenerator:0 - Compiling project 'NHibernate.Test' completed
     [exec] 22:03:11,463 INFO  AsyncCodeGenerator:0 - Initializing registered plugins for project 'NHibernate.Test' started
     [exec] 22:03:11,490 FATAL Program:0 - System.InvalidOperationException: Unable to find NUnit.Framework.Assert type
     [exec]    at AsyncGenerator.Core.Plugins.NUnitAsyncCounterpartsFinder.Initialize(Project project, IProjectConfiguration configuration, Compilation compilation)
     [exec]    at AsyncGenerator.AsyncCodeGenerator.<GenerateProject>d__3.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at AsyncGenerator.AsyncCodeGenerator.<GenerateAsync>d__1.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at AsyncGenerator.CommandLine.Program.Main(String[] args)
```

I assume it is not handling the multiple target frameworks in [the test .csproj file](https://github.com/ngbrown/nhibernate-core/blob/NH-3807-Async/src/NHibernate.Test/NHibernate.Test.csproj).

Will your pull request handle this?

**Comment by maca88** [comment]
> Will your pull request handle this?

No.

By doing some testing, I was able to make it work by explicitly setting the target framework when opening a project (by adding `["TargetFramework"] = "net461"` after [this](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator/AsyncCodeGenerator.cs#L94) line). I will [add an option](https://github.com/maca88/AsyncGenerator/issues/76) for setting the target framework for which the code will be generated.

**Comment by maca88** [comment]
@ngbrown with the version `0.8.0`, I've added the `targetFramework` option to set the desired target framework. Use this option for all projects that are using multiple target frameworks. [Here](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator.Tests/TargetFramework/Fixture.cs#L67) you can see where the new option should be.

**Comment by ngbrown** [comment]
@maca88 the error is still the same in `0.8.0`.  I noticed in your fixture, that you didn't use `<TargetFrameworks/>` (with the '__s__').

The `NHibernate.Test.csproj` needs to have a line like this:

```xml
    <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>
```

Feel free to to pull my branch to test: https://github.com/ngbrown/nhibernate-core/tree/NH-3807-Async

**Comment by hazzik** [comment]
@maca88 I'm getting following error on my branch https://github.com/hazzik/nhibernate-core/tree/netcoreapp2.0
```
- System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no matching element
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <3fb92ec709f44a579da6a23087df403d>:0 
  at AsyncGenerator.Transformation.Internal.ProjectTransformer.TransformDocument (AsyncGenerator.Core.Analyzation.IDocumentAnalyzationResult documentResult) [0x0000f] in <f4f2b726021743a79412e423cf09d68c>:0 
  at AsyncGenerator.Transformation.Internal.ProjectTransformer+<>c__DisplayClass22_0.<Transform>g__TransfromDocument|0 (AsyncGenerator.Core.Analyzation.IDocumentAnalyzationResult document) [0x00000] in <f4f2b726021743a79412e423cf09d68c>:0 
  at System.Threading.Tasks.Parallel+<>c__DisplayClass42_0`2[TSource,TLocal].<PartitionerForEachWorker>b__1 () [0x00287] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Task.InnerInvokeWithArg (System.Threading.Tasks.Task childTask) [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Task+<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0 (System.Object <p0>) [0x00086] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal] (System.Collections.Concurrent.Partitioner`1[TSource] source, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action`1[T] simpleBody, System.Action`2[T1,T2] bodyWithState, System.Action`3[T1,T2,T3] bodyWithStateAndIndex, System.Func`4[T1,T2,T3,TResult] bodyWithStateAndLocal, System.Func`5[T1,T2,T3,T4,TResult] bodyWithEverything, System.Func`1[TResult] localInit, System.Action`1[T] localFinally) [0x001fb] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal] (System.Collections.Generic.IEnumerable`1[T] source, System.Threading.Tasks.ParallelOptions parallelOptions, System.Action`1[T] body, System.Action`2[T1,T2] bodyWithState, System.Action`3[T1,T2,T3] bodyWithStateAndIndex, System.Func`4[T1,T2,T3,TResult] bodyWithStateAndLocal, System.Func`5[T1,T2,T3,T4,TResult] bodyWithEverything, System.Func`1[TResult] localInit, System.Action`1[T] localFinally) [0x0005e] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Parallel.ForEach[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Action`1[T] body) [0x0001c] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at AsyncGenerator.Transformation.Internal.ProjectTransformer.Transform (AsyncGenerator.Core.Analyzation.IProjectAnalyzationResult analyzationResult) [0x00041] in <f4f2b726021743a79412e423cf09d68c>:0 
  at AsyncGenerator.AsyncCodeGenerator.TransformProject (AsyncGenerator.Core.Analyzation.IProjectAnalyzationResult analyzationResult, AsyncGenerator.Configuration.Internal.ProjectTransformConfiguration configuration, AsyncGenerator.Core.Logging.ILoggerFactory loggerFactory) [0x00007] in <f4f2b726021743a79412e423cf09d68c>:0 
  at AsyncGenerator.AsyncCodeGenerator+<GenerateProject>d__2.MoveNext () [0x00470] in <f4f2b726021743a79412e423cf09d68c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at AsyncGenerator.AsyncCodeGenerator+<GenerateAsync>d__0.MoveNext () [0x00561] in <f4f2b726021743a79412e423cf09d68c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at AsyncGenerator.CommandLine.Program.Main (System.String[] args) [0x000bf] in <3d757e8da270452faf1011da48c35812>:0 
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no matching element
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <3fb92ec709f44a579da6a23087df403d>:0 
  at AsyncGenerator.Transformation.Internal.ProjectTransformer.TransformDocument (AsyncGenerator.Core.Analyzation.IDocumentAnalyzationResult documentResult) [0x0000f] in <f4f2b726021743a79412e423cf09d68c>:0 
  at AsyncGenerator.Transformation.Internal.ProjectTransformer+<>c__DisplayClass22_0.<Transform>g__TransfromDocument|0 (AsyncGenerator.Core.Analyzation.IDocumentAnalyzationResult document) [0x00000] in <f4f2b726021743a79412e423cf09d68c>:0 
  at System.Threading.Tasks.Parallel+<>c__DisplayClass42_0`2[TSource,TLocal].<PartitionerForEachWorker>b__1 () [0x00287] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Task.InnerInvokeWithArg (System.Threading.Tasks.Task childTask) [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at System.Threading.Tasks.Task+<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0 (System.Object <p0>) [0x00086] in <4fdc5ed61a074cafb49fa42deb20d521>:0 <---

```

**Comment by maca88** [comment]
@hazzik The generator had problems with ["empty files"](https://github.com/maca88/AsyncGenerator/issues/79), in your case it was [TestContext.cs](https://github.com/hazzik/nhibernate-core/blob/netcoreapp2.0/src/NHibernate.Test/TestsContext.cs). The issue was resolved within the version `0.8.2`.

**Comment by hazzik** [comment]
Thanks

**Comment by Sebazzz** [comment]
For .NET Core support you might be able to use [Buildalyzer](https://github.com/daveaglick/Buildalyzer) which allows properly setting up a roslyn workspace without the dependency on MSBuild. It has a dependency on the .NET SDK instead. I have successfully used it for codegen in my own project.

**Comment by maca88** [comment]
@Sebazzz thanks for the repo. I've tried Buildalyzer on .NET Framework but unfortunately, it seems that Buildalyzer has a problem with projects that have an import tag like [NHibernate project does](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/NHibernate.csproj#L2).
Logs:
```
INFO  - Opening project 'C:\NHibernate\Source\src\NHibernate\NHibernate.csproj' started
FATAL - Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\NHibernate\build-common\NHibernate.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```
where the correct path should be `C:\NHibernate\Source\build-common\NHibernate.props`.
