### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#33]
For some reasons now I'm getting a NullReferenceException when run from console (I was getting it from tests as well, but it disappeared). 

The exception:
```
     [exec] AsyncGenerator
     [exec]
     [exec] 10:50:59,166 INFO  AsyncCodeGenerator:0 - Generating async code started
     [exec] 10:50:59,181 INFO  AsyncCodeGenerator:0 - Configuring solution 'D:\Projects\nhibernate-core\src\NHibernate.s
ln' prior analyzation started
     [exec] 10:51:01,278 INFO  AsyncCodeGenerator:0 - Configuring solution 'D:\Projects\nhibernate-core\src\NHibernate.s
ln' prior analyzation completed
     [exec] 10:51:01,286 INFO  AsyncCodeGenerator:0 - Initializing registered plugins for project 'NHibernate' started
     [exec] 10:51:01,288 INFO  AsyncCodeGenerator:0 - Initializing registered plugins for project 'NHibernate' completed

     [exec] 10:51:01,292 INFO  AsyncCodeGenerator:0 - Analyzing project 'NHibernate' started
     [exec] 10:51:01,307 INFO  ProjectAnalyzer:0 - Parsing documents started
     [exec] 10:51:03,071 INFO  ProjectAnalyzer:0 - Parsing documents completed
     [exec] 10:51:03,073 INFO  ProjectAnalyzer:0 - Pre-analyzing documents started
     [exec] 10:51:05,976 INFO  ProjectAnalyzer:0 - Pre-analyzing documents completed
     [exec] 10:51:05,976 INFO  ProjectAnalyzer:0 - Scanning references started
     [exec] System.NullReferenceException: Object reference not set to an instance of an object.
     [exec]    at AsyncGenerator.Internal.ProjectData.GetFunctionData(IMethodSymbol methodSymbol)
     [exec]    at AsyncGenerator.Internal.ProjectData.GetMethodData(IMethodSymbol symbol)
     [exec]    at AsyncGenerator.Analyzation.Internal.ProjectAnalyzer.<ScanAllMethodReferenceLocations>d__33.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     [exec]    at AsyncGenerator.Analyzation.Internal.ProjectAnalyzer.<ScanMethodData>d__28.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     [exec]    at AsyncGenerator.Analyzation.Internal.ProjectAnalyzer.<ScanAllMethodReferenceLocations>d__33.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     [exec]    at AsyncGenerator.Analyzation.Internal.ProjectAnalyzer.<ScanMethodData>d__28.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     [exec]    at AsyncGenerator.Analyzation.Internal.ProjectAnalyzer.<ScanAllMethodReferenceLocations>d__33.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     [exec]    at AsyncGenerator.Analyzation.Internal.ProjectAnalyzer.<ScanMethodData>d__28.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     [exec]    at AsyncGenerator.Analyzation.Internal.ProjectAnalyzer.<ScanAllMethodReferenceLocations>d__33.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     [exec]    at AsyncGenerator.Analyzation.Internal.ProjectAnalyzer.<ScanMethodData>d__28.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at AsyncGenerator.Analyzation.Internal.ProjectAnalyzer.<ScanDocumentData>d__23.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at AsyncGenerator.Analyzation.Internal.ProjectAnalyzer.<Analyze>d__45.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     [exec]    at AsyncGenerator.AsyncCodeGenerator.<GenerateAsync>d__1.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at AsyncGenerator.CommandLine.Program.Main(String[] args)
```

**Comment by hazzik** [comment]
This morning I uninstalled the VS2017 community and repaired VS2017 community preview. Not sure how this can be related.

**Comment by hazzik** [comment]
It seems that MSBuildWorkplace could not load projects, and Roslyn itself is not really helpful at all.

**Comment by hazzik** [comment]
It seems uninstallation did not cause that. I'm having the same problem on my laptop as well. The cause is VS2017 Preview itself and the way Roslyn finds MSBuild. By default, Roslyn resolves latest MSBuild. In this case, it is 15.3 from VS2017 Preview. So, as we do not have binding redirect - the error happens.
