### ISSUE TITLE
The generator does not work when Visual Studio 15.6.3 is installed

### ISSUE THREAD

**Issue by maca88** [maca88/AsyncGenerator#87]
The following message is displayed:
```
[exec] FATAL CommandLine:0 - System.InvalidOperationException: One or more errors occurred while opening the project:
[exec] Msbuild failed when processing the file 'C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator.Tests\ExternalProjects\NHibernate\Source\src\NHibernate\NHibernate.csproj' with message: MSB0001: Internal MSBuild Error: Missing resource ''
[exec] Hint: For suppressing irrelevant errors use SuppressDiagnosticFailures option.
[exec]    at AsyncGenerator.AsyncCodeGenerator.CheckForErrors(MSBuildWorkspace workspace, String itemType, ImmutableArray`1 supressFailuresPredicates, ILogger logger)
[exec]    at AsyncGenerator.AsyncCodeGenerator.<OpenProject>d__8.MoveNext()
[exec] --- End of stack trace from previous location where exception was thrown ---
[exec]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[exec]    at AsyncGenerator.AsyncCodeGenerator.<GenerateAsync>d__0.MoveNext()
[exec] --- End of stack trace from previous location where exception was thrown ---
[exec]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[exec]    at AsyncGenerator.CommandLine.Program.Main(String[] args)
```

**Comment by fredericDelaporte** [comment]
Thanks for fixing this so fast. So that was not really a bug in MsBuid, but a matter of being forced to update the generator for using latest version?

**Comment by maca88** [comment]
As explained [here](https://github.com/nhibernate/nhibernate-core/pull/1620#issuecomment-374737459), the previous versions of `MSBuild` (prior `15.6`) didn't filtered out abstract classes that inherited from `SdkResolver`, when creating new instances. As they added an abstract class that inherits from `SdkResolver` in `MSBuild` `15.6`, we were forced to upgrade `MSBuild,` otherwise we wouldn't.
